# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
{ on  = [ "<C-s>" ], run  = 'shell fish --block --confirm', desc = "Drop to shell" },
{ on  = [ "<C-k>" ], run = 'shell kitty --confirm --orphan' , desc = "Open terminal here" },
]

