[plugin]
prepend_previewers = [
  { mime = "application/{,g}zip", run = "ouch" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar,iso9660-image}", run = "ouch" },
  { mime = "text/*", run = "bat" },
  { mime = "application/json", run = "bat" },
  { mime = "*/{xml,javascript,x-wine-extension-ini}", run = "bat" },
]
