[opener]
extract = [{ run = 'ouch decompress "$@"', block = false }]
[[plugin.prepend_previewers]]
mime = "application/{,g}zip"
run = "ouch"
[[plugin.prepend_previewers]]
mime = "application/x-{tar,bzip*,7z-compressed,xz,rar,iso9660-image}"
run = "ouch"
[[plugin.prepend_previewers]]
mime = "text/*"
run = "bat"
[[plugin.prepend_previewers]]
mime = "application/json"
run = "bat"
[[plugin.prepend_previewers]]
mime = "*/{xml,javascript,x-wine-extension-ini}"
run = "bat"
